# Generated by Django 3.2.9 on 2022-01-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('profile', models.CharField(choices=[('C', 'Cherry'), ('O', 'OEM'), ('X', 'XDA')], default='C', max_length=1)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.keyboard')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
