# Generated by Django 3.2.9 on 2022-01-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_keycaps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keycaps',
            new_name='Keycap',
        ),
    ]
