# Generated by Django 3.2.9 on 2022-01-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_stablizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='stablizers',
            field=models.ManyToManyField(to='main_app.Stablizer'),
        ),
    ]
